name: Main GitHub Actions
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14.x'
    - name: Install dependencies
      run: npm ci
    - name: Install Cypress
      run: npm install cypress --save-dev
    - name: Install cypress-cucumber-preprocessor
      run: npm install @badeball/cypress-cucumber-preprocessor
    - name: Install cypress-browserify-preprocessor
      run: npm install --save-dev @cypress/browserify-preprocessor
    - name: Install reporter dev
      run: npm install --save-dev mocha-allure-reporter allure-commandline
    - name: Run Playwright tests
      run: npm run test
    - name: Generate Report
      if: always()
      run: npm run allure-generate
    - name: Upload Results
      uses: actions/upload-artifact@v1
      if: always()
      with:
          name: allure-results
          path: ./allure-results
    - name: Publishing Allure artifact to Github Actions
      uses: actions/upload-artifact@v2
      if: always()
      with:
          name: allure-report
          path: allure-report   
    - name: Deploy report
      uses: JamesIves/github-pages-deploy-action@4.1.4
      if: always()
      with:
          branch: gh-pages 
          folder: allure-report
